routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified', 'approved_user']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::post('/', 'HomeController@postDashboard');
    Route::post('/dashboard', 'HomeController@postDashboard');
    Route::get('/member/{id}', 'HomeController@profile');
});


Route::group(['middleware' => ['auth', 'verified', 'approved_user', 'authorized:ADMIN,MODERATOR']], function () {
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::resource('department', 'DepartmentController');
    Route::resource('session', 'SessionController');
    Route::resource('batch', 'BatchController');
    Route::get('/pending/users', 'HomeController@getPendingUser');
    Route::post('/registration/approve', 'HomeController@approveUser');
    Route::post('/registration/decline', 'HomeController@declineUser');
    Route::resource('occupation', 'OccupationController');

    Route::get('/pending/emails', 'UserController@getPendingEmail')->name('pending_emails');
    Route::post('/email/verify', 'UserController@approveEmail')->name('email_verify');
    Route::get('/active/users', 'UserController@activeUser')->name('active_users');
    Route::post('/account/deactivate', 'UserController@deactivateAccount')->name('account_deactivate');
    Route::get('/deactivate/users', 'UserController@deactivateUser')->name('deactivate_users');
    Route::post('/account/activate', 'UserController@activateAccount')->name('account_activate');






});


Route::group(['middleware' => ['auth', 'verified', 'authorized:ADMIN']], function () {
    Route::get('/export/{data}', 'HomeController@export');
});


Route::get('get-cities/{id}', function ($id) {
    return json_encode(\App\City::where('state_id', $id)->get());
});
Route::get('get-department-short-codes/{id}', function ($id) {
    return json_encode(\App\Department::where('id', $id)->get());
});
Route::get('get-batches/{id}', function ($id) {
    return json_encode(\App\Session::where('id', $id)->get());
});
Route::get('get-states/{id}', function ($id) {
    return json_encode(\App\State::where('country_id', $id)->get());
});


Route::get('/about-us', function () {
    return view('frontend.about-us.about-us');
});
Route::get('/blog', function () {
    return view('frontend.blog.blog');
});
Route::get('/contact-us', function () {
    return view('frontend.contact-us.contact-us');
});
Route::get('/news-and-events', function () {
    return view('frontend.news-and-events.news-and-events');
});
Route::get('/privacy-policy', function () {
    return view('frontend.privacy-policy.privacy-policy');
});

resources/views/backend/layouts/partials/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class=" text-center my-auto">
            <span class="text-blue" target="blank">Developed by</span> <span  style="text-decoration: underline;"><a href="https://ogroni.com/" class="text-black" target="blank">Ogroni Informatix Limited</a></span>
        </div>
    </div>
</footer>

resources/views/backend/layouts/partials/header.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                <img class="img-profile rounded-circle" alt="user-image"
                     src={{url('storage/'.Auth::user()->profile->picture) }}>
            </a>
            <!-- Dropdown - UserController Information -->
            <div class=" dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{url('member/'.Auth::user()->profile->id)}}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/backend/layouts/partials/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="https://sustian.xyz">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> SUSTIAN Professional Network</div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
        <a class="nav-link" href="{{url('/dashboard')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{url('/news-and-events')}}">
            <i class="fa fa-book"></i>
            <span>News and Events</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{url('/about-us')}}">
            <i class="fa fa-book" aria-hidden="true"></i>
            <span>About Us</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{url('/privacy-policy')}}">
            <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
            <span>Privacy Policy</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{url('/contact-us')}}">
            <i class="fa fa-phone-square" aria-hidden="true"></i>
            <span>Contact Us</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{url('/blog')}}">
            <i class="fas fa-blog"></i>
            <span>Blog</span></a>
    </li>
    @if (Auth::user()->role == 'ADMIN' || Auth::user()->role == 'MODERATOR')
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
               aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-folder"></i>
                <span>Admin Setup</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{{route('country.index')}}">Country</a>
                    <a class="collapse-item" href="{{route('state.index')}}">State</a>
                    <a class="collapse-item" href="{{route('city.index')}}">City</a>
                    <a class="collapse-item" href="{{route('department.index')}}">Department</a>
                    <a class="collapse-item" href="{{route('session.index')}}">Session</a>
                    <a class="collapse-item" href="{{route('occupation.index')}}">Occupation</a>
                    <a class="collapse-item" href="{{url('/pending/users')}}">Pending Users</a>
                    <a class="collapse-item" href="{{route('pending_emails')}}">Pending Emails</a>
                    <a class="collapse-item" href="{{route('active_users')}}">Active Users</a>
                    <a class="collapse-item" href="{{route('deactivate_users')}}">Deactivate Users</a>



                </div>
            </div>
        </li>
    @endif

    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>