routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified', 'approved_user']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::post('/', 'HomeController@postDashboard');
    Route::post('/dashboard', 'HomeController@postDashboard');
    Route::get('/member/{id}', 'HomeController@profile');
});


Route::group(['middleware' => ['auth', 'verified', 'approved_user', 'authorized:ADMIN,MODERATOR']], function () {
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::resource('department', 'DepartmentController');
    Route::resource('session', 'SessionController');
    Route::resource('batch', 'BatchController');
    Route::get('/pending/users', 'HomeController@getPendingUser');
    Route::post('/registration/approve', 'HomeController@approveUser');
    Route::post('/registration/decline', 'HomeController@declineUser');
    Route::resource('occupation', 'OccupationController');

    Route::get('/pending/emails', 'UserController@getPendingEmail')->name('pending_emails');
    Route::post('/email/verify', 'UserController@approveEmail')->name('email_verify');
    Route::get('/active/users', 'UserController@activeUser')->name('active_users');
    Route::post('/account/deactivate', 'UserController@deactivateAccount')->name('account_deactivate');
    Route::get('/deactivate/users', 'UserController@deactivateUser')->name('deactivate_users');
    Route::post('/account/activate', 'UserController@activateAccount')->name('account_activate');






});


Route::group(['middleware' => ['auth', 'verified', 'authorized:ADMIN']], function () {
    Route::get('/export/{data}', 'HomeController@export');
});


Route::get('get-cities/{id}', function ($id) {
    return json_encode(\App\City::where('state_id', $id)->get());
});
Route::get('get-department-short-codes/{id}', function ($id) {
    return json_encode(\App\Department::where('id', $id)->get());
});
Route::get('get-batches/{id}', function ($id) {
    return json_encode(\App\Session::where('id', $id)->get());
});
Route::get('get-states/{id}', function ($id) {
    return json_encode(\App\State::where('country_id', $id)->get());
});


Route::get('/about-us', function () {
    return view('frontend.about-us.about-us');
});
Route::get('/blog', function () {
    return view('frontend.blog.blog');
});
Route::get('/contact-us', function () {
    return view('frontend.contact-us.contact-us');
});
Route::get('/news-and-events', function () {
    return view('frontend.news-and-events.news-and-events');
});
Route::get('/privacy-policy', function () {
    return view('frontend.privacy-policy.privacy-policy');
});

app/Session.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Session extends Model
{
    protected $fillable = ['session', 'batch_number'];

    public function profiles()
    {
        return $this->hasMany(Profile::class);
    }
}

app/Http/Controllers/SessionController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\Session;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class SessionController extends Controller
{
    public function index()
    {

        $sl = !is_null(\request()->page) ? (\request()->page-1) * 10 : 0;
        $sessions =Session::orderBy('created_at','desc')->paginate(10);

        return view('backend.session.index', compact('sessions','sl'));
    }


    public function create()
    {

        return view('backend.session.create');
    }


    public function store(Request $request)
    {
//        dd($request->all());
        try {
            $request->validate([
                'session' => ['required', 'string', 'max:255'],
                'batch_number' => ['required', 'string', 'max:255'],
            ]);
            $sessions = $request->all();

            Session::create($sessions);

            return redirect()->route('session.index')->withStatus('Created successfully!');
        }catch (QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function edit(Session $session)
    {

        return view('backend.session.edit', compact('session'));
    }

    public function update(Request $request, Session $session)
    {
        try{

            $session->update($request->all());
            return redirect()->route('session.index')->withStatus('Updated successfully!');
        }catch (QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }

    }
}

resources/views/backend/session/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Session Create')

@section('content')
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-6">Create Session</div>
                    <div class="col-md-6 text-right">
                        <a href="{{ route('session.index') }}" class="btn btn-sm btn-outline-primary">List</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {{ Form::open(['route'=>'session.store',
                           'files'=>true,
                           ])}}

                @include('backend.session.form')


                {{Form::button('SAVE',[
                                 'class'=>'btn btn-primary',
                                 'type'=>'submit',
                                    ])}}

                {{--            </form>--}}
                {{ Form::close()}}
            </div>
        </div>
    </div>
@endsection

resources/views/backend/session/edit.blade.php
@extends('backend.layouts.master')

@section('title', 'Session Edit')

@section('content')
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-6">Edit Session</div>
                    <div class="col-md-6 text-right">
                        <a href="{{ route('session.index') }}" class="btn btn-sm btn-outline-primary">List</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {{Form::model($session, [
                      'route'=>['session.update',
                      $session->id],
                      'files'=>true,
                      'method'=>'put',
                 ])}}
                @csrf
                @method('PUT')

                @include('backend.session.form')

                {{Form::button('Update',[
                                'class'=>'btn btn-primary',
                                'type'=>'submit',
                                   ])}}
                {{ Form::close()}}
            </div>
        </div>
    </div>
@endsection

resources/views/backend/session/form.blade.php
            <div class="form-row">
                <div class="col-md-12 mb-3">
                    {{Form::label('session','Session')}}
                    {{Form::text('session', null, [
                          'class'=> $errors->has('session') ?  'form-control is-invalid': 'form-control',
                          'placeholder'=>'Enter The session ',
                          'id'=>'session',
                    ])}}
                    @error('session')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror

                </div>
            </div>

            <div class="form-row">
                <div class="col-md-12 mb-3">
                    {{Form::label('batch_number','Batch Number')}}
                    {{Form::text('batch_number', null, [
                          'class'=> $errors->has('batch_number') ?  'form-control is-invalid': 'form-control',
                          'placeholder'=>'Enter The batch number',
                          'id'=>'batch_number',
                    ])}}
                    @error('batch_number')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror

                </div>
            </div>

resources/views/backend/session/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Session')

@section('content')
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-6">Session</div>
                    <div class="col-md-6 text-right">
                        <a href="{{ route('session.create') }}" class="btn btn-sm btn-outline-primary">Add New</a>

                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered"  width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#SL</th>
                            <th>Session</th>
                            <th>Batch Number</th>

                            <th style="width: 150px; text-align: center;">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if(session()->has('status'))
                            <div class="alert alert-success">

                                <p>{{session('status')}}</p>

                            </div>
                        @endif

                        @foreach($sessions as $session)
                            <tr>
                                <td>{{++$sl}}</td>

                                <td>{{$session->session}}</td>
                                <td>{{$session->batch_number}}</td>


                                <td>
{{--                                    <a href="{{ route('country.show', $country->id) }}" class="btn btn-sm btn-outline-info">Show</a>--}}
                                    <a href="{{ route('session.edit', $session->id) }}" class="btn btn-sm btn-outline-warning">Edit</a>
                                    {{--                            <a href="#" class="btn btn-sm btn-outline-danger">Delete</a>--}}
{{--                                    <form action="{{route('country.destroy', $country->id)}}" method="post">--}}
{{--                                        @csrf--}}
{{--                                        @method('DELETE')--}}
{{--                                        <button class="btn btn-outline-danger" type="submit" onclick="return confirm('Are you sure Want to delete?')">Delete</button>--}}

{{--                                    </form>--}}


                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $sessions->links() }}
            </div>

        </div>

    </div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('script')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush